{{- if .Values.vllm.phi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vllm-local-swarm.fullname" . }}-vllm-phi
  labels:
    {{- include "vllm-local-swarm.vllm-phi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.vllm.phi.service.type }}
  ports:
    - port: {{ .Values.vllm.phi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vllm-local-swarm.vllm-phi.selectorLabels" . | nindent 4 }}
{{- end }}