apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vllm-local-swarm.fullname" . }}-secrets
  labels:
    {{- include "vllm-local-swarm.labels" . | nindent 4 }}
type: Opaque
data:
  # Langfuse secrets
  langfuse-secret-key: {{ .Values.secrets.langfuse.secretKey | b64enc | quote }}
  langfuse-salt: {{ .Values.secrets.langfuse.salt | b64enc | quote }}
  langfuse-encryption-key: {{ .Values.secrets.langfuse.encryptionKey | b64enc | quote }}
  
  # ClickHouse secrets
  clickhouse-password: {{ .Values.secrets.clickhouse.password | b64enc | quote }}
  
  {{- if .Values.secrets.openai.apiKey }}
  # OpenAI secrets
  openai-api-key: {{ .Values.secrets.openai.apiKey | b64enc | quote }}
  {{- end }}