name: 🐛 Bug Report
description: Report a bug or issue with vLLM Local Swarm
title: "🐛 [BUG]: "
labels: ["bug", "needs-triage"]
assignees:
  - tbowman01

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        
        Thanks for reporting a bug! Please provide detailed information to help us reproduce and fix the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have read the project README and documentation
          required: true
        - label: I am using the latest version from main branch
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component/Service Affected
      description: Which component is experiencing the issue?
      options:
        - Authentication Service (port 8005)
        - Memory API (port 8003)
        - Orchestrator (port 8004)
        - vLLM Model Serving (port 8000/8001)
        - Ray Cluster (port 8265)
        - Langfuse (port 3000)
        - Qdrant Vector DB (port 6333)
        - Redis (port 6379)
        - Docker Compose/Deployment
        - GitHub Actions CI/CD
        - GHCR Container Registry
        - Other (please specify)
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System completely unusable)
        - High (Major functionality broken)
        - Medium (Feature partially working)
        - Low (Minor issue or cosmetic)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: List the exact steps to reproduce the bug
      placeholder: |
        1. Run command: `make up`
        2. Navigate to service endpoint
        3. Perform action...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: Describe expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe actual behavior...
    validations:
      required: true

  - type: textarea
    id: error_logs
    attributes:
      label: Error Logs/Output
      description: Include relevant error messages, stack traces, or log output
      placeholder: |
        # Docker logs
        docker-compose logs [service-name]
        
        # Or specific error messages
        
      render: bash

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Your system environment details
      placeholder: |
        - OS: Ubuntu 22.04 / Windows 11 / macOS 14
        - Docker: 24.0.0
        - Docker Compose: 2.20.0
        - Python: 3.11
        - GPU: NVIDIA RTX 4090 (if applicable)
        - Memory: 32GB RAM
        - Deployment: Local / Docker / GHCR containers
      render: markdown

  - type: textarea
    id: system_status
    attributes:
      label: System Status Check
      description: Output from health check commands
      placeholder: |
        # Service health check
        make health-check
        
        # Container status
        docker-compose ps
        
        # System resources
        docker stats --no-stream
      render: bash

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or relevant information
      placeholder: |
        - Screenshots
        - Configuration changes made
        - Recent updates or changes
        - Related issues or PRs

  - type: checkboxes
    id: testing_done
    attributes:
      label: Testing Done
      description: What testing have you performed?
      options:
        - label: Reproduced on clean environment
        - label: Checked Docker logs for errors
        - label: Verified with latest main branch
        - label: Tested with fresh containers (`make clean && make up`)
        - label: Checked system resources (CPU/Memory/Disk)

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this fix?
      options:
        - Urgent (Blocking critical functionality)
        - High (Important feature affected)
        - Medium (Normal bug fix)
        - Low (Nice to have fix)
    validations:
      required: true