blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation & Quick Start
    url: https://github.com/tbowman01/vllm-local-swarm/blob/main/README.md
    about: Check the README and documentation for setup instructions
  
  - name: 💬 GitHub Discussions
    url: https://github.com/tbowman01/vllm-local-swarm/discussions
    about: Ask questions, share ideas, and discuss the project
  
  - name: 🔒 Private Security Report
    url: mailto:security@example.com
    about: Report critical security vulnerabilities privately (email for responsible disclosure)
    
  - name: 🤖 Claude Code Support
    url: https://claude.ai/code
    about: Get help with Claude Code integration and usage