name: 🔒 Security Vulnerability Report
description: Report a security vulnerability (CONFIDENTIAL)
title: "🔒 [SECURITY]: "
labels: ["security", "critical", "confidential"]
assignees:
  - tbowman01

body:
  - type: markdown
    attributes:
      value: |
        ## 🔒 Security Vulnerability Report
        
        **⚠️ IMPORTANT**: For critical security vulnerabilities, please report privately via email to ensure responsible disclosure.
        
        **Email**: [Security contact information]
        
        This template is for non-critical security improvements and general security discussions.

  - type: checkboxes
    id: responsible_disclosure
    attributes:
      label: Responsible Disclosure
      description: Security reporting acknowledgment
      options:
        - label: This is NOT a critical security vulnerability requiring private disclosure
          required: true
        - label: I understand this issue will be publicly visible immediately
          required: true
        - label: For critical vulnerabilities, I will email instead of using this form
          required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: CVSS-based severity assessment
      options:
        - Low (CVSS 0.1-3.9) - Minimal impact
        - Medium (CVSS 4.0-6.9) - Moderate impact  
        - High (CVSS 7.0-8.9) - Significant impact
        - Critical (CVSS 9.0-10.0) - **EMAIL REQUIRED**
    validations:
      required: true

  - type: dropdown
    id: vulnerability_type
    attributes:
      label: Vulnerability Type
      description: Category of security issue
      options:
        - Authentication Bypass
        - Authorization/Access Control
        - Injection (SQL/NoSQL/Command)
        - Cross-Site Scripting (XSS)
        - Cross-Site Request Forgery (CSRF)
        - Insecure Deserialization
        - Security Misconfiguration
        - Sensitive Data Exposure
        - Insufficient Logging/Monitoring
        - Container Security
        - API Security
        - Cryptographic Issue
        - Dependency Vulnerability
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: affected_component
    attributes:
      label: Affected Component
      description: Which component has the vulnerability?
      options:
        - Authentication Service (JWT/API Keys)
        - Authorization Middleware
        - Memory API (Data Access)
        - Orchestrator API
        - vLLM Model Serving
        - Database (PostgreSQL)
        - Redis Cache
        - Vector Database (Qdrant)
        - Docker Configuration
        - GitHub Actions/CI
        - GHCR Container Images
        - Network Configuration
        - Multiple Components
        - Other (specify)
    validations:
      required: true

  - type: textarea
    id: vulnerability_description
    attributes:
      label: Vulnerability Description
      description: Detailed description of the security issue
      placeholder: |
        Provide a clear description of the vulnerability:
        - What is the security flaw?
        - How does it manifest?
        - What are the security implications?
    validations:
      required: true

  - type: textarea
    id: attack_scenario
    attributes:
      label: Attack Scenario
      description: How could an attacker exploit this vulnerability?
      placeholder: |
        Describe the attack scenario:
        1. Attacker prerequisites/access needed
        2. Steps to exploit the vulnerability
        3. What the attacker gains/achieves
        
        Note: Provide enough detail for reproduction but avoid detailed exploit code.

  - type: textarea
    id: impact_assessment
    attributes:
      label: Impact Assessment
      description: What are the potential impacts?
      placeholder: |
        Security impact analysis:
        - Confidentiality: What data could be exposed?
        - Integrity: What data/systems could be modified?
        - Availability: What services could be disrupted?
        - Scope: How many users/systems affected?

  - type: textarea
    id: technical_details
    attributes:
      label: Technical Details
      description: Technical information about the vulnerability
      placeholder: |
        Technical analysis:
        - Code location/file paths
        - Configuration issues
        - Network protocols involved
        - Authentication/authorization bypassed
        - Data flow compromised
      render: markdown

  - type: textarea
    id: proof_of_concept
    attributes:
      label: Proof of Concept
      description: Evidence demonstrating the vulnerability (be responsible)
      placeholder: |
        Responsible proof of concept:
        - Screenshots of security test results
        - Log entries showing the issue
        - Network traces (sanitized)
        - Code snippets (without exploit details)
        
        DO NOT include:
        - Full exploit code
        - Actual sensitive data
        - Ways to cause harm to production systems

  - type: textarea
    id: environment_details
    attributes:
      label: Environment Details
      description: Environment where vulnerability was discovered
      placeholder: |
        Environment information:
        - OS and version
        - Docker/container versions
        - Network configuration
        - Authentication setup
        - Deployment method (local/GHCR/etc.)

  - type: textarea
    id: remediation_suggestions
    attributes:
      label: Suggested Remediation
      description: Your recommendations for fixing this vulnerability
      placeholder: |
        Remediation suggestions:
        - Immediate mitigation steps
        - Code changes needed
        - Configuration improvements
        - Security controls to implement
        - Testing recommendations

  - type: checkboxes
    id: security_testing
    attributes:
      label: Security Testing Performed
      description: What security testing was done?
      options:
        - label: Manual security testing
        - label: Automated vulnerability scanning
        - label: Code review for security flaws
        - label: Authentication/authorization testing
        - label: Input validation testing
        - label: Network security assessment

  - type: textarea
    id: references
    attributes:
      label: References & Resources
      description: Relevant security references
      placeholder: |
        Security references:
        - CVE identifiers
        - OWASP references
        - Security advisories
        - Related vulnerabilities
        - Security best practice guides

  - type: dropdown
    id: disclosure_timeline
    attributes:
      label: Disclosure Preference
      description: Preferred disclosure timeline
      options:
        - Immediate (Non-sensitive issue)
        - Coordinated (30 days)
        - Extended (60-90 days for complex issues)
        - Already publicly known
    validations:
      required: true

  - type: checkboxes
    id: security_commitment
    attributes:
      label: Security Commitment
      description: Security reporting ethics
      options:
        - label: I will not share exploit details publicly until fixed
          required: true
        - label: I will not access/modify production data without permission
          required: true
        - label: I understand this affects a security-first project with strict standards
          required: true
        - label: I am committed to responsible disclosure practices
          required: true