# Qdrant Configuration for vLLM Local Swarm Semantic Memory

log_level: INFO

storage:
  # Storage path for collections
  storage_path: /qdrant/storage
  
  # Storage configuration
  snapshots_path: /qdrant/snapshots
  
  # Performance settings
  performance:
    max_search_threads: 0  # Use all available cores
    
  # Optimistic optimizations for better performance
  optimizers:
    deleted_threshold: 0.2
    vacuum_min_vector_number: 1000
    default_segment_number: 0
    max_segment_size: 5000000
    memmap_threshold: 1000000
    indexing_threshold: 20000
    flush_interval_sec: 5
    max_optimization_threads: 1

service:
  # HTTP API settings
  http_port: 6333
  grpc_port: 6334
  
  # Enable CORS for web access
  enable_cors: true
  
  # API key authentication (optional)
  # api_key: ${QDRANT_API_KEY}
  
  # Maximum request size
  max_request_size_mb: 32
  
  # Maximum concurrent requests
  max_workers: 0  # Use all available cores

cluster:
  # Enable if running in cluster mode
  enabled: false
  
  # Node configuration
  # p2p:
  #   port: 6335
  
  # consensus:
  #   tick_period_ms: 100

# Telemetry settings
telemetry_disabled: true

# Collection settings (default)
collection:
  # Default vector configuration
  vectors:
    size: 384  # Default embedding size (sentence-transformers/all-MiniLM-L6-v2)
    distance: Cosine
    
  # Optimizer configuration
  optimizer_config:
    deleted_threshold: 0.2
    vacuum_min_vector_number: 1000
    default_segment_number: 0
    max_segment_size: 5000000
    memmap_threshold: 1000000
    indexing_threshold: 20000
    flush_interval_sec: 5
    max_optimization_threads: 1
    
  # WAL configuration
  wal_config:
    wal_capacity_mb: 32
    wal_segments_ahead: 0
    
  # HNSW configuration for vector indexing
  hnsw_config:
    m: 16
    ef_construct: 100
    full_scan_threshold: 10000
    max_indexing_threads: 0
    on_disk: false
    payload_m: 16

# Resource limits
limits:
  # Memory limits
  max_request_size_mb: 32
  
  # Threading limits
  max_workers: 0
  max_search_threads: 0