apiVersion: v2
name: vllm-local-swarm
description: A Helm chart for vLLM Local Swarm - Collaborative AI with Local Performance
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - ai
  - llm
  - vllm
  - ray
  - swarm
  - collaborative
home: https://github.com/your-org/vllm-local-swarm
sources:
  - https://github.com/your-org/vllm-local-swarm
maintainers:
  - name: vLLM Local Swarm Team
    email: team@example.com
dependencies:
  - name: redis
    version: 18.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  category: AI/ML